name: py309_statistics

channels:
    - defaults

dependencies:
    - python==3.9.7  # The first line should always be python version
    - pip
    - pillow
    - jupyter
    - sympy
    - matplotlib
    - pip: # only by pip
        - pipdeptree # or conda install -c conda-forge pipdeptree
        - symbulate
